-- Migration 004: seed all product slugs referenced in field guide articles
-- that are missing from the products table.
-- affiliate_url uses tag=bayshine-20 as placeholder — replace with real Amazon Associates ID.
-- Run: DATABASE_URL=... node scripts/run-migration.mjs migrations/004_missing_products.sql

INSERT INTO products (slug, name, brand, description, task_tags, affiliate_url, active)
VALUES
  ('303-aerospace-protectant',
   '303 Aerospace Protectant', '303',
   'UV protectant for interior and exterior plastics, rubber, vinyl, and trim. Prevents fading and cracking.',
   ARRAY['trim','interior','uv-protection'],
   'https://www.amazon.com/s?k=303+aerospace+protectant&tag=bayshine-20', true),

  ('aio-polish',
   'Chemical Guys All-In-One Polish & Sealant', 'Chemical Guys',
   'All-in-one polish with light cutting, gloss enhancement, and sealant protection in a single pass.',
   ARRAY['polish','correction','sealant'],
   'https://www.amazon.com/s?k=chemical+guys+all+in+one+polish+sealant&tag=bayshine-20', true),

  ('apc-concentrate',
   'All Purpose Cleaner Concentrate', 'Chemical Guys',
   'Dilutable APC for interior surfaces, engine bays, wheels, and general decontamination. Dilute to task.',
   ARRAY['interior','engine','decon','utility'],
   'https://www.amazon.com/s?k=chemical+guys+all+purpose+cleaner+concentrate&tag=bayshine-20', true),

  ('applicator-cloths',
   'Foam Applicator Pads', 'Chemical Guys',
   'Round foam applicator pads for even product application — wax, sealant, interior dressings.',
   ARRAY['wax','sealant','application'],
   'https://www.amazon.com/s?k=foam+applicator+pads+car+detailing&tag=bayshine-20', true),

  ('biocide-mold-treatment',
   'Biocide Systems Auto Shocker', 'Biocide Systems',
   'Chlorine dioxide odor eliminator for mold, mildew, and biological odors in car interiors.',
   ARRAY['odor','mold','interior'],
   'https://www.amazon.com/s?k=biocide+systems+auto+shocker&tag=bayshine-20', true),

  ('bug-remover-spray',
   'Bugs N All Bug Remover', 'Griot''s Garage',
   'Pre-soak spray that loosens insect splatter, tar, and road grime before washing.',
   ARRAY['decon','bugs','exterior'],
   'https://www.amazon.com/s?k=bug+remover+spray+car+detailing&tag=bayshine-20', true),

  ('car-shampoo',
   'pH-Neutral Car Wash Shampoo', 'Chemical Guys',
   'Concentrated pH-neutral shampoo for safe washing on sealed, waxed, or ceramic-coated surfaces.',
   ARRAY['wash','exterior'],
   'https://www.amazon.com/s?k=ph+neutral+car+wash+shampoo&tag=bayshine-20', true),

  ('carpro-reload',
   'CarPro Reload Spray Sealant', 'CarPro',
   'SiO2 spray sealant that bonds to ceramic coatings and bare paint. 6-month durability.',
   ARRAY['sealant','coating','maintenance'],
   'https://www.amazon.com/s?k=carpro+reload+spray+sealant&tag=bayshine-20', true),

  ('ceramic-vinyl-ppf',
   'Ceramic Coating for Vinyl and PPF', 'Gtechniq',
   'Ceramic coating formulated for vinyl wrap and paint protection film surfaces.',
   ARRAY['coating','vinyl','ppf'],
   'https://www.amazon.com/s?k=ceramic+coating+vinyl+wrap&tag=bayshine-20', true),

  ('chemical-guys-iron-remover',
   'Chemical Guys DeCon Pro Iron Remover', 'Chemical Guys',
   'Ferrous iron decontamination spray. Turns purple on contact with iron particles embedded in paint and wheels.',
   ARRAY['decon','iron','paint','wheels'],
   'https://www.amazon.com/s?k=chemical+guys+iron+remover+decon&tag=bayshine-20', true),

  ('clay-bar-kit',
   'Meguiar''s Smooth Surface Clay Kit', 'Meguiar''s',
   'Clay bar kit with 2 bars and detailer spray. Medium grade — removes bonded contamination from paint.',
   ARRAY['clay','decon','paint'],
   'https://www.amazon.com/s?k=meguiars+smooth+surface+clay+kit&tag=bayshine-20', true),

  ('clay-luber',
   'Detailing Clay Lubricant Spray', 'Adam''s Polishes',
   'Slick clay bar lubricant that reduces drag and prevents marring during clay bar decontamination.',
   ARRAY['clay','decon','lubricant'],
   'https://www.amazon.com/s?k=clay+bar+lubricant+spray+detailing&tag=bayshine-20', true),

  ('convertible-top-cleaner',
   'Raggtopp Convertible Top Cleaner', 'Wolfsteins',
   'Convertible soft top cleaner for cloth and vinyl fabric. Removes mold, dirt, and oxidation.',
   ARRAY['convertible','trim','cleaning'],
   'https://www.amazon.com/s?k=raggtopp+convertible+top+cleaner&tag=bayshine-20', true),

  ('convertible-top-protectant',
   'Raggtopp Convertible Top Protectant', 'Wolfsteins',
   'UV and water protectant for cloth convertible tops. Seals fabric against Florida UV fading.',
   ARRAY['convertible','trim','uv-protection'],
   'https://www.amazon.com/s?k=raggtopp+convertible+top+protectant&tag=bayshine-20', true),

  ('detail-brush-set',
   'Detailing Brush Set', 'Chemical Guys',
   'Assorted soft-bristle detailing brushes for wheels, vents, emblems, and trim crevices.',
   ARRAY['brushes','wheels','interior','trim'],
   'https://www.amazon.com/s?k=car+detailing+brush+set&tag=bayshine-20', true),

  ('detailer-spray',
   'Quick Detailer Spray', 'Adam''s Polishes',
   'Waterless detailer for light dust and fingerprints between washes on sealed or coated paint.',
   ARRAY['maintenance','exterior','quick-detail'],
   'https://www.amazon.com/s?k=quick+detailer+spray+car&tag=bayshine-20', true),

  ('detailing-brush-set',
   'Interior Detailing Brush Set', 'Mothers',
   'Soft-bristle brushes for dashboard vents, trim seams, and tight interior spaces.',
   ARRAY['interior','brushes','trim'],
   'https://www.amazon.com/s?k=interior+detailing+brush+set+car&tag=bayshine-20', true),

  ('di-water-filter',
   'Deionized Water Filter for Spot-Free Rinse', 'CR Spotless',
   'Inline water deionizer for spot-free final rinse. Eliminates mineral deposits from hard water.',
   ARRAY['washing','spot-free','minerals'],
   'https://www.amazon.com/s?k=deionized+water+filter+car+wash&tag=bayshine-20', true),

  ('dreadnought-drying-towel',
   'Chemical Guys Woolly Mammoth Microfiber Dryer', 'Chemical Guys',
   'Extra-large high-GSM drying towel for fast, scratch-free drying on full-size vehicles.',
   ARRAY['drying'],
   'https://www.amazon.com/s?k=chemical+guys+woolly+mammoth+drying+towel&tag=bayshine-20', true),

  ('drying-towel',
   'High-GSM Drying Towel', 'The Rag Company',
   'Professional-grade 1100 GSM waffle weave drying towel for water absorption without dragging.',
   ARRAY['drying'],
   'https://www.amazon.com/s?k=microfiber+drying+towel+car+high+gsm&tag=bayshine-20', true),

  ('engine-bay-dressing',
   'Engine Bay Dressing', '303',
   'Water-based engine bay dressing for plastic and rubber surfaces. Non-greasy, UV-protective finish.',
   ARRAY['engine','trim','uv-protection'],
   'https://www.amazon.com/s?k=engine+bay+dressing+car&tag=bayshine-20', true),

  ('engine-degreaser',
   'Engine Degreaser Spray', 'Chemical Guys',
   'Concentrated engine degreaser for removing oil, grease, and road grime from engine bays.',
   ARRAY['engine','degreaser','cleaning'],
   'https://www.amazon.com/s?k=engine+degreaser+spray+car&tag=bayshine-20', true),

  ('enzyme-interior-cleaner',
   'Enzyme Interior Cleaner', 'Biokleen',
   'Enzyme-based cleaner that breaks down protein-based stains and odors in fabric and carpet.',
   ARRAY['interior','enzyme','odor','stain'],
   'https://www.amazon.com/s?k=enzyme+cleaner+car+interior&tag=bayshine-20', true),

  ('enzyme-odor-eliminator',
   'Enzyme Odor Eliminator Spray', 'Zero Odor',
   'Enzyme formula that eliminates mold, pet, and smoke odors at the molecular level.',
   ARRAY['odor','enzyme','interior'],
   'https://www.amazon.com/s?k=enzyme+odor+eliminator+car+interior&tag=bayshine-20', true),

  ('evap-coil-cleaner',
   'No-Rinse Evaporator Coil Cleaner', 'Nu-Calgon',
   'HVAC evaporator coil cleaner for eliminating mold and odor at the AC evaporator source.',
   ARRAY['hvac','odor','mold'],
   'https://www.amazon.com/s?k=evaporator+coil+cleaner+car+ac&tag=bayshine-20', true),

  ('fabric-protector',
   'Scotchgard Fabric Protector for Auto', '3M',
   'Spray fabric protector for cloth seats and carpets. Repels water and blocks stain absorption.',
   ARRAY['fabric','interior','protection'],
   'https://www.amazon.com/s?k=scotchgard+fabric+protector+auto&tag=bayshine-20', true),

  ('foam-applicator',
   'Foam Applicator Pad', 'Chemical Guys',
   'High-density foam applicator for wax, sealant, and interior dressing application.',
   ARRAY['application','wax','sealant'],
   'https://www.amazon.com/s?k=foam+applicator+pad+detailing&tag=bayshine-20', true),

  ('foam-cannon',
   'MTM Hydro PF22 Foam Cannon', 'MTM Hydro',
   'Professional foam cannon with adjustable foam output for pressure washer pre-wash applications.',
   ARRAY['washing','foam','exterior'],
   'https://www.amazon.com/s?k=foam+cannon+pressure+washer+car&tag=bayshine-20', true),

  ('glass-towel-set',
   'The Rag Company Minx Glass Towel Set', 'The Rag Company',
   'Silk-edge glass towels designed for streak-free automotive glass cleaning.',
   ARRAY['glass','cleaning'],
   'https://www.amazon.com/s?k=the+rag+company+glass+towel+car&tag=bayshine-20', true),

  ('griots-garage-ceramic-3in1',
   'Griot''s Garage Ceramic 3-in-1', 'Griot''s Garage',
   'Polish, cleaner, and SiO2 ceramic protection in one step. Removes light defects while adding a ceramic layer.',
   ARRAY['polish','ceramic','protection'],
   'https://www.amazon.com/s?k=griots+garage+ceramic+3+in+1&tag=bayshine-20', true),

  ('grit-guard',
   'Grit Guard Insert', 'Grit Guard',
   'Bucket insert that traps grit at the bottom and prevents contamination of wash mitt during two-bucket wash.',
   ARRAY['washing','grit-guard','two-bucket'],
   'https://www.amazon.com/s?k=grit+guard+bucket+insert+car+wash&tag=bayshine-20', true),

  ('interior-brush',
   'Soft Interior Detail Brush', 'Detail Factory',
   'Extra-soft bristle brush for dashboard vents, speaker grilles, and soft-touch interior surfaces.',
   ARRAY['interior','brushes'],
   'https://www.amazon.com/s?k=soft+interior+detail+brush+car&tag=bayshine-20', true),

  ('ipa-prep',
   'IPA Surface Prep Wipe', 'Chemical Guys',
   'Isopropyl alcohol panel wipe spray for removing oils and residue before ceramic coating application.',
   ARRAY['coating-prep','ipa','panel-prep'],
   'https://www.amazon.com/s?k=ipa+isopropyl+alcohol+car+detailing+prep&tag=bayshine-20', true),

  ('ipa-surface-prep',
   'IPA Panel Prep Solution', 'CarPro',
   'Diluted IPA surface preparation spray. Removes polishing oils before sealant or ceramic application.',
   ARRAY['coating-prep','ipa','panel-prep'],
   'https://www.amazon.com/s?k=ipa+surface+prep+car+detailing&tag=bayshine-20', true),

  ('ir-thermometer',
   'Infrared Thermometer Gun', 'Etekcity',
   'Non-contact IR thermometer for measuring panel surface temperature before applying coatings and polishes.',
   ARRAY['tools','temperature','coating'],
   'https://www.amazon.com/s?k=infrared+thermometer+gun&tag=bayshine-20', true),

  ('iron-fallout-remover',
   'Iron Fallout Remover Spray', 'CarPro Iron X',
   'pH-balanced iron decontamination spray. Turns purple and dissolves embedded iron particles on contact.',
   ARRAY['decon','iron','paint','wheels'],
   'https://www.amazon.com/s?k=iron+fallout+remover+spray+car&tag=bayshine-20', true),

  ('iron-x',
   'CarPro Iron X', 'CarPro',
   'Professional-grade iron fallout remover. Strong pH-balanced formula for paint, wheels, and glass.',
   ARRAY['decon','iron','paint','wheels'],
   'https://www.amazon.com/s?k=carpro+iron+x+decontamination&tag=bayshine-20', true),

  ('lake-country-cutting',
   'Lake Country Cutting Pad', 'Lake Country',
   'Orange cutting foam pad for heavy defect removal with rotary or dual-action polisher.',
   ARRAY['correction','polishing','pad'],
   'https://www.amazon.com/s?k=lake+country+cutting+pad+foam&tag=bayshine-20', true),

  ('leather-cleaner-ph',
   'Leather Honey Leather Cleaner', 'Leather Honey',
   'pH-balanced leather cleaner for automotive seats. Removes dirt and oil without drying the leather.',
   ARRAY['leather','interior','cleaning'],
   'https://www.amazon.com/s?k=leather+honey+cleaner+car+seats&tag=bayshine-20', true),

  ('leather-conditioner',
   'Leather Honey Leather Conditioner', 'Leather Honey',
   'Penetrating leather conditioner that restores flexibility and prevents cracking in Florida UV and heat.',
   ARRAY['leather','interior','conditioning'],
   'https://www.amazon.com/s?k=leather+honey+conditioner+car+seats&tag=bayshine-20', true),

  ('matte-detailer',
   'Matte Paint Quick Detailer', 'Adam''s Polishes',
   'Matte-safe quick detailer for matte, satin, and flat paint finishes. No gloss agents.',
   ARRAY['matte','exterior','maintenance'],
   'https://www.amazon.com/s?k=matte+paint+quick+detailer+car&tag=bayshine-20', true),

  ('meguiars-water-spot-remover',
   'Meguiar''s Water Spot Remover', 'Meguiar''s',
   'Citric acid-based water spot remover for dissolving mineral deposits from paint and glass.',
   ARRAY['water-spots','paint','glass'],
   'https://www.amazon.com/s?k=meguiars+water+spot+remover&tag=bayshine-20', true),

  ('menzerna-2400',
   'Menzerna Super Finish 2400', 'Menzerna',
   'Ultra-fine finishing polish for removing light haze from polished paint before sealant application.',
   ARRAY['polish','finishing','correction'],
   'https://www.amazon.com/s?k=menzerna+super+finish+2400&tag=bayshine-20', true),

  ('menzerna-400',
   'Menzerna Heavy Cut Compound 400', 'Menzerna',
   'Heavy cutting compound for deep scratch and buffer trail removal. Use with cutting pad on DA or rotary.',
   ARRAY['compound','correction','heavy-cut'],
   'https://www.amazon.com/s?k=menzerna+heavy+cut+compound+400&tag=bayshine-20', true),

  ('menzerna-hc400',
   'Menzerna Heavy Cut 400', 'Menzerna',
   'High-cut compound with controlled diminishing abrasives for efficient paint correction.',
   ARRAY['compound','correction','heavy-cut'],
   'https://www.amazon.com/s?k=menzerna+hc400+compound&tag=bayshine-20', true),

  ('menzerna-sf3500',
   'Menzerna Super Finish 3500', 'Menzerna',
   'Pure finishing polish with ultra-fine abrasives. Final step before coating or wax application.',
   ARRAY['polish','finishing','correction'],
   'https://www.amazon.com/s?k=menzerna+sf3500+finishing+polish&tag=bayshine-20', true),

  ('microfiber-revitalizer',
   'Microfiber Revitalizer', 'Chemical Guys',
   'Microfiber-safe laundry additive that removes wax, polish, and silicone from towels during wash.',
   ARRAY['microfiber','laundry','maintenance'],
   'https://www.amazon.com/s?k=microfiber+revitalizer+detailing+towels&tag=bayshine-20', true),

  ('microfiber-wash-mitt',
   'Microfiber Wash Mitt', 'The Rag Company',
   'Plush microfiber wash mitt with deep pile to safely trap and release grit during the wash phase.',
   ARRAY['washing','mitt','exterior'],
   'https://www.amazon.com/s?k=microfiber+wash+mitt+car&tag=bayshine-20', true),

  ('nanoskin-autoscrub-fine',
   'Nanoskin AutoScrub Fine Grade Pad', 'Nanoskin',
   'Surface decontamination scrubbing pad — clay bar alternative. Fine grade for regular maintenance use.',
   ARRAY['clay','decon','paint'],
   'https://www.amazon.com/s?k=nanoskin+autoscrub+fine+decon&tag=bayshine-20', true),

  ('paint-thickness-gauge',
   'Digital Paint Thickness Gauge', 'LS220',
   'Magnetic and eddy-current paint depth gauge for measuring clear coat thickness before correction.',
   ARRAY['tools','measurement','correction'],
   'https://www.amazon.com/s?k=paint+thickness+gauge+car+detailing&tag=bayshine-20', true),

  ('ph-neutral-wash',
   'pH-Neutral Car Wash Soap', 'Optimum',
   'No-rinse or bucket pH-neutral wash formula safe for all paint protection levels.',
   ARRAY['washing','exterior','ph-neutral'],
   'https://www.amazon.com/s?k=ph+neutral+car+wash+soap&tag=bayshine-20', true),

  ('polymer-sealant',
   'Synthetic Polymer Paint Sealant', 'Wolfgang',
   'Cross-linked polymer sealant with 6-month durability in Florida UV. Hard gloss, UV-blocking formula.',
   ARRAY['sealant','paint','protection'],
   'https://www.amazon.com/s?k=synthetic+polymer+paint+sealant+car&tag=bayshine-20', true),

  ('rupes-lhr15',
   'Rupes LHR15 Mark III Dual Action Polisher', 'Rupes',
   'Professional 15mm throw random orbital polisher. The industry standard for safe paint correction.',
   ARRAY['polisher','correction','tools'],
   'https://www.amazon.com/s?k=rupes+lhr15+random+orbital+polisher&tag=bayshine-20', true),

  ('sap-remover',
   'Tree Sap Remover', 'Turtle Wax',
   'Solvent-based tree sap and tar remover. Dissolves bonded organic contamination without scrubbing.',
   ARRAY['decon','sap','tar','exterior'],
   'https://www.amazon.com/s?k=tree+sap+remover+car+paint&tag=bayshine-20', true),

  ('snow-foam-shampoo',
   'Snow Foam Pre-Wash Shampoo', 'Chemical Guys',
   'Thick snow foam formula for foam cannon pre-wash. Lifts surface contamination before contact washing.',
   ARRAY['washing','foam','pre-wash'],
   'https://www.amazon.com/s?k=snow+foam+car+shampoo+foam+cannon&tag=bayshine-20', true),

  ('soft-top-mold-cleaner',
   'Star Brite Fabric & Canvas Cleaner', 'Star Brite',
   'Fabric canvas cleaner with mold inhibitor for soft-top convertibles. Marine-grade formula.',
   ARRAY['convertible','mold','trim','cleaning'],
   'https://www.amazon.com/s?k=star+brite+fabric+canvas+cleaner&tag=bayshine-20', true),

  ('upholstery-stain-remover',
   'Folex Instant Carpet Spot Remover', 'Folex',
   'Water-based stain remover safe for all fabric types. Works on seats, carpets, and headliners.',
   ARRAY['interior','stain','fabric','carpet'],
   'https://www.amazon.com/s?k=folex+carpet+spot+remover&tag=bayshine-20', true),

  ('uv-interior-protectant',
   'Meguiar''s Quik Interior Detailer', 'Meguiar''s',
   'UV-blocking interior protectant spray for dashboard, trim, and door panels.',
   ARRAY['interior','uv-protection','trim'],
   'https://www.amazon.com/s?k=meguiars+interior+detailer+uv+protectant&tag=bayshine-20', true),

  ('water-spot-remover',
   'Chemical Guys Heavy Duty Water Spot Remover', 'Chemical Guys',
   'Oxalic acid formula for dissolving stage 2 and 3 water spot etching on paint and glass.',
   ARRAY['water-spots','paint','glass'],
   'https://www.amazon.com/s?k=chemical+guys+water+spot+remover&tag=bayshine-20', true),

  ('wet-dry-vac-upholstery',
   'Shop-Vac with Upholstery Attachment', 'Shop-Vac',
   'High-CFM wet/dry vacuum with upholstery nozzle for deep extraction from fabric seats and carpet.',
   ARRAY['interior','extraction','vacuum'],
   'https://www.amazon.com/s?k=shop+vac+upholstery+attachment+car&tag=bayshine-20', true),

  ('wheel-brush-set',
   'Wheel and Barrel Brush Set', 'Chemical Guys',
   'Wheel well brush, barrel brush, and lug nut brush set for complete wheel face and barrel cleaning.',
   ARRAY['wheels','brushes','cleaning'],
   'https://www.amazon.com/s?k=wheel+brush+set+car+detailing&tag=bayshine-20', true),

  ('work-horse-microfiber',
   'Utility Microfiber Towel Pack', 'The Rag Company',
   'Value-pack utility microfibers for decon work, iron remover wipe-off, and wheel cleaning.',
   ARRAY['utility','decon','wheels'],
   'https://www.amazon.com/s?k=utility+microfiber+towel+pack+detailing&tag=bayshine-20', true),

  ('wrap-wash-soap',
   'Adam''s Wrap Wash', 'Adam''s Polishes',
   'pH-neutral soap formulated for vinyl wrap. No wax or gloss agents that build up on matte finish.',
   ARRAY['vinyl','wrap','washing'],
   'https://www.amazon.com/s?k=adams+polishes+wrap+wash&tag=bayshine-20', true)

ON CONFLICT (slug) DO NOTHING;
